global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['eoracle-data-fetcher:<PROMETHEUS_PORT>']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']