global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'eoracle-data-validator'
    static_configs:
      - targets: ['eoracle-data-validator:<PROMETHEUS_PORT>']
      