version: "3.8"
services:
  data-validator:
    env_file:
      - .env
    container_name: eoracle-data-validator
    ports:
      - ${EO_PROMETHEUS_PORT}:${EO_PROMETHEUS_PORT}
      - ${EO_HEALTH_ENDPOINTS_PORT}:${EO_HEALTH_ENDPOINTS_PORT}
    volumes:
      - ./${EO_KEYSTORE_PATH}:/app/${EO_KEYSTORE_PATH}:rw
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    image: ${EO_DATA_VALIDATOR_IMAGE}
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - eoracle-data-validator
networks:
  eoracle-data-validator:
    name: eoracle-data-validator
