{
 "title": "Data Validators ext",
 "tags": [
  "eoracle",
  "validators"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "data_validator",
    "query": {
     "query": "label_values(eigen_performance_score,app)"
    }
   },
   { "name": "data_source", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Data Validator $data_validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "data_validator" },
  {
   "title": "Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_performance_score{app=~\"$data_validator\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "RPC Req",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_rpc_request_total{app=~\"$data_validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eOracle Errors Avg 5 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "rate(eoracle_failures{app=~\"$data_validator\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Rate Duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_rpc_request_duration_seconds_bucket{app=~\"$data_validator\", le=~\"(0.005|0.01|0.025|0.05|0.1|0.25|0.5|1)\"} / ignoring(le) group_left eigen_rpc_request_duration_seconds_bucket{app=~\"$data_validator\", le=\"+Inf\"}*100",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "eOracle Chain",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eoracle_performance_bucket{app=~\"$data_validator\", le=~\"(0.001|0.005|0.01|0.025|0.05|0.1|0.25|0.5|1)\"} / ignoring(le) group_left eoracle_performance_bucket{app=~\"$data_validator\", le=\"+Inf\"}*100",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "eOracle Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eoracle_failures{app=~\"$data_validator\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Data Providers $data_validator",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "eoracle_health_check{app=~\"$data_validator\",name!~\"(service|value)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}